import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./context/themeProvider";

export const metadata: Metadata = {
  title: "Solana Data Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body>{children}</body> 
      </Providers>
    </html>
  );
}
